# Generated by Django 5.2.9 on 2025-12-04 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(db_index=True, help_text='Unique identifier for a query request', max_length=64, unique=True, verbose_name='Query ID')),
                ('encrypted_location_x', models.TextField(help_text='X coordinate ciphertext using Paillier homomorphic encryption', verbose_name='Encrypted X Coordinate')),
                ('encrypted_location_y', models.TextField(help_text='Y coordinate ciphertext using Paillier homomorphic encryption', verbose_name='Encrypted Y Coordinate')),
                ('encrypted_keywords', models.TextField(help_text='Encrypted keyword list stored in JSON format', verbose_name='Encrypted Keywords')),
                ('text_weight', models.FloatField(default=0.5, help_text='Text similarity weight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Text Weight')),
                ('distance_weight', models.FloatField(default=0.5, help_text='Distance similarity weight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Distance Weight')),
                ('top_k', models.IntegerField(default=10, help_text='Return top K most similar results', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Top-K Results')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Query Status')),
                ('is_continuous', models.BooleanField(default=False, help_text='Whether this is a continuous spatial query requiring real-time location updates', verbose_name='Is Continuous')),
                ('encrypted_results', models.TextField(blank=True, help_text='Encrypted Top-K results stored in JSON format', null=True, verbose_name='Encrypted Results')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store additional query-related information like query time, processing nodes, etc.', verbose_name='Query Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_queries', to=settings.AUTH_USER_MODEL, verbose_name='Query User')),
            ],
            options={
                'verbose_name': 'Secure Query',
                'verbose_name_plural': 'Secure Queries',
                'db_table': 'secure_query',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(help_text='e.g.: query_received, index_search, fog_computation, result_returned', max_length=50, verbose_name='Log Type')),
                ('message', models.TextField(verbose_name='Log Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Log Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='secure_query.securequery', verbose_name='Query')),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'db_table': 'query_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('default_text_weight', models.FloatField(default=0.5, help_text='Text similarity weight, range 0-1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Default Text Weight')),
                ('default_distance_weight', models.FloatField(default=0.5, help_text='Distance similarity weight, range 0-1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Default Distance Weight')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='securequery',
            index=models.Index(fields=['user', 'status', 'created_at'], name='secure_quer_user_id_1aeba8_idx'),
        ),
        migrations.AddIndex(
            model_name='securequery',
            index=models.Index(fields=['query_id'], name='secure_quer_query_i_145596_idx'),
        ),
        migrations.AddIndex(
            model_name='securequery',
            index=models.Index(fields=['is_continuous', 'status'], name='secure_quer_is_cont_833e72_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['query', 'created_at'], name='query_log_query_i_5d1346_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['log_type', 'created_at'], name='query_log_log_typ_1fcfea_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'is_active'], name='user_profil_user_id_4a8e08_idx'),
        ),
    ]
