# Generated by Django 5.2.9 on 2025-12-04 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(db_index=True, help_text='唯一标识一次查询请求', max_length=64, unique=True, verbose_name='查询ID')),
                ('encrypted_location_x', models.TextField(help_text='使用Paillier同态加密的X坐标密文', verbose_name='加密X坐标')),
                ('encrypted_location_y', models.TextField(help_text='使用Paillier同态加密的Y坐标密文', verbose_name='加密Y坐标')),
                ('encrypted_keywords', models.TextField(help_text='JSON格式存储的加密关键词列表', verbose_name='加密关键词集合')),
                ('text_weight', models.FloatField(default=0.5, help_text='文本相似度权重', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='文本权重')),
                ('distance_weight', models.FloatField(default=0.5, help_text='距离相似度权重', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='距离权重')),
                ('top_k', models.IntegerField(default=10, help_text='返回前K个最相似的结果', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Top-K结果数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='查询状态')),
                ('is_continuous', models.BooleanField(default=False, help_text='是否为连续空间查询，需要实时更新位置', verbose_name='是否连续查询')),
                ('encrypted_results', models.TextField(blank=True, help_text='JSON格式存储的加密Top-K结果', null=True, verbose_name='加密查询结果')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储查询相关的额外信息，如查询时间、处理节点等', verbose_name='查询元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_queries', to=settings.AUTH_USER_MODEL, verbose_name='查询用户')),
            ],
            options={
                'verbose_name': '安全查询',
                'verbose_name_plural': '安全查询',
                'db_table': 'secure_query',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(help_text='如：query_received, index_search, fog_computation, result_returned等', max_length=50, verbose_name='日志类型')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='日志元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='secure_query.securequery', verbose_name='关联查询')),
            ],
            options={
                'verbose_name': '查询日志',
                'verbose_name_plural': '查询日志',
                'db_table': 'query_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('default_text_weight', models.FloatField(default=0.5, help_text='文本相似度权重，范围0-1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='默认文本权重')),
                ('default_distance_weight', models.FloatField(default=0.5, help_text='距离相似度权重，范围0-1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='默认距离权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='securequery',
            index=models.Index(fields=['user', 'status', 'created_at'], name='secure_quer_user_id_1aeba8_idx'),
        ),
        migrations.AddIndex(
            model_name='securequery',
            index=models.Index(fields=['query_id'], name='secure_quer_query_i_145596_idx'),
        ),
        migrations.AddIndex(
            model_name='securequery',
            index=models.Index(fields=['is_continuous', 'status'], name='secure_quer_is_cont_833e72_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['query', 'created_at'], name='query_log_query_i_5d1346_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['log_type', 'created_at'], name='query_log_log_typ_1fcfea_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'is_active'], name='user_profil_user_id_4a8e08_idx'),
        ),
    ]
