# Generated by Django 5.2.9 on 2025-12-04 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='所有者ID')),
                ('public_key', models.TextField(help_text='Paillier同态加密的公钥，用于加密数据', verbose_name='公钥')),
                ('total_objects', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总对象数')),
                ('encrypted_objects', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='已加密对象数')),
                ('index_built', models.BooleanField(default=False, help_text='KASTree索引是否已构建完成', verbose_name='索引是否已构建')),
                ('index_version', models.CharField(blank=True, help_text='索引的版本号，用于版本管理', max_length=32, null=True, verbose_name='索引版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_owner', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '数据所有者',
                'verbose_name_plural': '数据所有者',
                'db_table': 'data_owner',
            },
        ),
        migrations.CreateModel(
            name='EncryptedSpatialObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, help_text='空间对象的唯一标识符', max_length=64, verbose_name='对象ID')),
                ('original_x', models.FloatField(blank=True, help_text='仅用于开发调试，生产环境应删除此字段', null=True, verbose_name='原始X坐标')),
                ('original_y', models.FloatField(blank=True, help_text='仅用于开发调试，生产环境应删除此字段', null=True, verbose_name='原始Y坐标')),
                ('encrypted_location_x', models.TextField(help_text='使用Paillier同态加密的X坐标密文', verbose_name='加密X坐标')),
                ('encrypted_location_y', models.TextField(help_text='使用Paillier同态加密的Y坐标密文', verbose_name='加密Y坐标')),
                ('encrypted_keywords', models.TextField(help_text='JSON格式存储的加密关键词列表', verbose_name='加密关键词集合')),
                ('encrypted_document', models.TextField(blank=True, help_text='对象的加密文档内容或标识', null=True, verbose_name='加密文档')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储对象的额外信息，如类别、标签等', verbose_name='对象元数据')),
                ('ktree_node_path', models.CharField(blank=True, help_text='该对象在KTree中的路径，用于索引检索', max_length=512, null=True, verbose_name='KTree节点路径')),
                ('ktree_region', models.IntegerField(blank=True, help_text='对象所属的KTree区域编号(0-3)', null=True, verbose_name='KTree区域编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_objects', to='data_owner.dataowner', verbose_name='数据所有者')),
            ],
            options={
                'verbose_name': '加密空间对象',
                'verbose_name_plural': '加密空间对象',
                'db_table': 'encrypted_spatial_object',
            },
        ),
        migrations.CreateModel(
            name='IndexMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktree_depth', models.IntegerField(default=0, help_text='KTree的深度(高度)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='KTree深度')),
                ('ktree_node_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KTree节点数')),
                ('ktree_leaf_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KTree叶子节点数')),
                ('spatial_domain_x_min', models.FloatField(help_text='数据空间域的X轴最小值', verbose_name='X轴最小值')),
                ('spatial_domain_x_max', models.FloatField(help_text='数据空间域的X轴最大值', verbose_name='X轴最大值')),
                ('spatial_domain_y_min', models.FloatField(help_text='数据空间域的Y轴最小值', verbose_name='Y轴最小值')),
                ('spatial_domain_y_max', models.FloatField(help_text='数据空间域的Y轴最大值', verbose_name='Y轴最大值')),
                ('assettree_size', models.IntegerField(default=0, help_text='AssetTree的节点数量', validators=[django.core.validators.MinValueValidator(0)], verbose_name='AssetTree大小')),
                ('index_storage_type', models.CharField(choices=[('redis', 'Redis'), ('cassandra', 'Cassandra'), ('file', '文件系统'), ('memory', '内存')], default='redis', max_length=20, verbose_name='索引存储类型')),
                ('index_storage_path', models.CharField(blank=True, help_text='索引在存储系统中的路径或键名', max_length=512, null=True, verbose_name='索引存储路径')),
                ('build_status', models.CharField(choices=[('not_started', '未开始'), ('building', '构建中'), ('completed', '已完成'), ('failed', '失败')], default='not_started', max_length=20, verbose_name='构建状态')),
                ('build_started_at', models.DateTimeField(blank=True, null=True, verbose_name='构建开始时间')),
                ('build_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='构建完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index_metadata', to='data_owner.dataowner', verbose_name='数据所有者')),
            ],
            options={
                'verbose_name': '索引元数据',
                'verbose_name_plural': '索引元数据',
                'db_table': 'index_metadata',
            },
        ),
        migrations.AddIndex(
            model_name='dataowner',
            index=models.Index(fields=['owner_id'], name='data_owner_owner_i_052b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='dataowner',
            index=models.Index(fields=['index_built'], name='data_owner_index_b_f5b5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedspatialobject',
            index=models.Index(fields=['data_owner', 'object_id'], name='encrypted_s_data_ow_5d8f71_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedspatialobject',
            index=models.Index(fields=['ktree_region', 'ktree_node_path'], name='encrypted_s_ktree_r_b8ee06_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedspatialobject',
            index=models.Index(fields=['created_at'], name='encrypted_s_created_61a301_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='encryptedspatialobject',
            unique_together={('data_owner', 'object_id')},
        ),
    ]
