# Generated by Django 5.2.9 on 2026-03-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_size', models.IntegerField(choices=[(512, '512 bit'), (1024, '1024 bit'), (2048, '2048 bit')], default=1024, verbose_name='密钥位长度')),
                ('public_key', models.TextField(help_text='Base64 编码的 Paillier 公钥', verbose_name='公钥（序列化）')),
                ('private_key', models.TextField(help_text='Base64 编码的 Paillier 私钥（演示环境存储）', verbose_name='私钥（序列化）')),
                ('public_key_digest', models.CharField(db_index=True, max_length=32, verbose_name='公钥摘要')),
                ('gen_time_ms', models.IntegerField(default=0, verbose_name='生成耗时(ms)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否为当前激活密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Paillier 密钥对',
                'verbose_name_plural': 'Paillier 密钥对',
                'db_table': 'keypair',
                'ordering': ['-created_at'],
            },
        ),
    ]
