# Generated by Django 5.2.9 on 2026-03-26 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_owner', '0002_add_keypair_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataowner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_owners', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
