# Generated by Django 5.2.9 on 2026-03-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_owner', '0003_alter_dataowner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedspatialobject',
            name='encrypted_name',
            field=models.TextField(blank=True, help_text='POI 可读名称的 Paillier 同态加密密文', null=True, verbose_name='加密名称'),
        ),
    ]
