# Generated by Django 5.2.9 on 2025-12-04 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FogNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='节点ID')),
                ('node_name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('maintenance', '维护中'), ('error', '错误')], db_index=True, default='inactive', max_length=20, verbose_name='节点状态')),
                ('host', models.CharField(help_text='雾节点的主机地址或IP', max_length=255, verbose_name='主机地址')),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='端口号')),
                ('max_concurrent_tasks', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大并发任务数')),
                ('current_tasks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='当前任务数')),
                ('total_tasks_processed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总处理任务数')),
                ('average_processing_time', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='平均处理时间(秒)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储节点的额外配置信息', verbose_name='节点元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='节点最后上报心跳的时间', null=True, verbose_name='最后心跳时间')),
            ],
            options={
                'verbose_name': '雾节点',
                'verbose_name_plural': '雾节点',
                'db_table': 'fog_node',
                'indexes': [models.Index(fields=['node_id', 'status'], name='fog_node_node_id_e7bbfd_idx'), models.Index(fields=['status', 'current_tasks'], name='fog_node_status_1c54d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComputationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='任务ID')),
                ('query_id', models.CharField(db_index=True, help_text='关联的查询请求ID', max_length=64, verbose_name='查询ID')),
                ('task_type', models.CharField(help_text='如：similarity_computation, distance_calculation等', max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('assigned', '已分配'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('timeout', '超时')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('encrypted_input_data', models.TextField(help_text='JSON格式存储的加密候选集数据', verbose_name='加密输入数据')),
                ('encrypted_output_data', models.TextField(blank=True, help_text='JSON格式存储的加密计算结果', null=True, verbose_name='加密输出数据')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储任务相关的额外信息', verbose_name='任务元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('fog_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='fog_node.fognode', verbose_name='分配的雾节点')),
            ],
            options={
                'verbose_name': '计算任务',
                'verbose_name_plural': '计算任务',
                'db_table': 'computation_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query_id', 'status'], name='computation_query_i_797915_idx'), models.Index(fields=['fog_node', 'status'], name='computation_fog_nod_2b191c_idx'), models.Index(fields=['task_type', 'status'], name='computation_task_ty_0c9d82_idx'), models.Index(fields=['created_at'], name='computation_created_a7f144_idx')],
            },
        ),
    ]
